In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0])

[1 2 3 4]


In [ ]:
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

In [3]:
import numpy as np

In [5]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
print (np.arange(4))
print(np.arange(0,10,2))

[0 1 2 3]
[0 2 4 6 8]


In [9]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [11]:
np.arange(4)

array([0, 1, 2, 3])

In [10]:
np.arange(0,10,2) #0 sampe 10 longkapnya dua

array([0, 2, 4, 6, 8])

In [13]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [11]:
np.arange(-2,29,5)

array([-2,  3,  8, 13, 18, 23, 28])

In [14]:
arr=np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.append(arr,[1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [16]:
#beda sama ini
x=[1,2]
x.append([10,11])
x

[1, 2, [10, 11]]

In [17]:
np.delete(arr,1)

array([1, 3, 4, 5, 6, 7, 8])

In [21]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
arr=np.array([[1,2,3,4,5,6,7,8],[3,4,5,1,2,6,7,5]])
arr

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [3, 4, 5, 1, 2, 6, 7, 5]])

In [19]:
np.sort(arr)

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 5, 6, 7]])

In [20]:
arr.ndim

2

In [21]:
arr.size

16

In [22]:
arr.shape

(2, 8)

In [39]:
arr3=np.array([[[0,1,2,3],
           [4,5,6,7]],
          
           [[0,1,2,3],
            [4,5,6,7]],
          
          [[0,1,2,3],
           [4,5,6,7]]])

arr3

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [40]:
arr3.ndim 

3

In [41]:
arr3.shape

(3, 2, 4)

In [42]:
arr3.size

24

In [45]:
arr4=np.arange(6)
arr4

array([0, 1, 2, 3, 4, 5])

In [46]:
arr4.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [48]:
arr4.shape

(6,)

In [25]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [26]:
a2=a[np.newaxis]
a2.shape

(1, 6)

In [27]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [28]:
row_vector=a[np.newaxis,:]
row_vector.shape

(1, 6)

In [29]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [31]:
col_vector=a[:,np.newaxis]
col_vector.shape

(6, 1)

In [ ]:
a=np.array([1,2,3,4,5,6])
a.shape

In [32]:
b=np.expand_dims(a,axis=1)
b.shape

(6, 1)

In [33]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [34]:
c=np.expand_dims(a,axis=0)
c.shape

(1, 6)

In [35]:
c

array([[1, 2, 3, 4, 5, 6]])

In [49]:
data=np.array([1,2,3])
data

array([1, 2, 3])

In [50]:
data[0]

1

In [51]:
data[1]

2

In [52]:
data[2]

3

In [54]:
data[0:2]

array([1, 2])

In [55]:
data[1:]

array([2, 3])

In [56]:
data[-2:]

array([2, 3])

In [57]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
condition=(a>=5)
a[condition]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
condition=(a%2==0)
a[condition]

array([ 2,  4,  6,  8, 10, 12])

In [62]:
condition=(a>2)&(a<11)
a[condition]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
a[(a>2)&(a<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
#creating array from existing data
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr1=arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [67]:
a1=np.array([[1,2],[2,2]])
a2=np.array([[3,3],[4,4]])


array([[3, 3],
       [4, 4]])

In [68]:
a1

array([[1, 2],
       [2, 2]])

In [69]:
a2

array([[3, 3],
       [4, 4]])

In [70]:
np.vstack((a1,a2))

array([[1, 2],
       [2, 2],
       [3, 3],
       [4, 4]])

In [71]:
np.hstack((a1,a2))

array([[1, 2, 3, 3],
       [2, 2, 4, 4]])

In [72]:
np.hstack((a1,a2))

array([[1, 2, 3, 3],
       [2, 2, 4, 4]])

In [74]:
arrsplit=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])
arrsplit

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [75]:
np.hsplit(arrsplit,3)

[array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16]),
 array([17, 18, 19, 20, 21, 22, 23, 24])]

In [76]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
a.shape

(3, 4)

In [78]:
b=a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
c=a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
#basic array operation
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [84]:
a.sum()

10

In [87]:
b=np.array([[1,1],[2,3]])
b

array([[1, 1],
       [2, 3]])

In [90]:
b.sum(axis=0)

array([3, 4])

In [91]:
b.sum(axis=1)

array([2, 5])

In [92]:
data=np.array([1,2])
data

array([1, 2])

In [94]:
ones=np.ones(2)
ones

array([1., 1.])

In [95]:
data+ones

array([2., 3.])

In [96]:
data*ones

array([1., 2.])

In [97]:
data/ones

array([1., 2.])

In [98]:
data-ones

array([0., 1.])

In [99]:
#broadcasting
data

array([1, 2])

In [100]:
data*1.6

array([1.6, 3.2])

In [101]:
#more array operation
data.max()

2

In [102]:
data.min()

1

In [103]:
data.sum()

3

In [104]:
#matrices
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [105]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [106]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [107]:
data+ones

array([2., 3.])

In [108]:
data-ones

array([0., 1.])

In [110]:
data/ones

array([1., 2.])

In [111]:
#dot productt
a1=np.array([[1,2,3],[4,5,6]])
a1.shape

(2, 3)

In [112]:
a2=np.array([[7,8],[9,10],[11,12]])
a2.shape

(3, 2)

In [113]:
np.dot(a1,a2)

array([[ 58,  64],
       [139, 154]])

In [114]:
#matrix indexing
data=np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [115]:
data[0,1]

2

In [116]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [117]:
data[0:2,1]

array([2, 4])

In [118]:
#matrix aggregation
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
data.max()

6

In [120]:
data.min()

1

In [121]:
data.sum()

21

In [122]:
data.std()

1.707825127659933

In [123]:
data.max(axis=0)

array([5, 6])

In [124]:
data.max(axis=1)

array([2, 4, 6])

In [125]:
#transposing and reshaping
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [127]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [128]:
data_col=np.array([[1,2,3,4,5,6]])
data_col

array([[1, 2, 3, 4, 5, 6]])

In [129]:
data_col=data_col.T
data_col

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [130]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [132]:
arr=np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [133]:
#N-dimensional array
ndarr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [134]:
ndarr.shape

(2, 2, 2)

In [135]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [137]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [138]:
np.random.random((4,3,2))

array([[[0.27877679, 0.13478662],
        [0.42174708, 0.34764347],
        [0.50617673, 0.1748148 ]],

       [[0.56004267, 0.61567347],
        [0.22035008, 0.28564532],
        [0.78033563, 0.2726517 ]],

       [[0.77151994, 0.89328965],
        [0.49515687, 0.52762681],
        [0.08238593, 0.90054303]],

       [[0.21473817, 0.89938313],
        [0.79829449, 0.25955103],
        [0.74309566, 0.12999421]]])

In [139]:
#flatten N-Dimensional Array
arrflat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arrflat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [140]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [141]:
arrflat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
error=(1/n)*np.sum(np.square(observed-prediction))